server:
  port: 8081

spring:
  datasource:
      url: jdbc:mysql://171.221.228.246:3306/sa?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root472
      driver-class-name: com.mysql.jdbc.Driver

